'use client';

import dynamic from 'next/dynamic';
import { useEffect, useState } from 'react';
import { trip, type TripDay } from '@/lib/trip';

const TripMap = dynamic(() => import('./TripMap'), { ssr:false, loading:() => <div className="empty-state">Loading route map…</div> });
type View = 'today'|'trip'|'map'|'bookings'|'readiness'|'journal';
type JournalEntry = { notes:string; moment:string; food:string; spend:string; rating:string };
type SavedState = { checks:Record<string,boolean>; selectedDayId:string; journal:Record<string,JournalEntry> };
const initial:SavedState = { checks:{}, selectedDayId:trip.days[0].id, journal:{} };
const storageKey = `atlas:${trip.id}:next`;
const emptyJournalEntry:JournalEntry = { notes:'', moment:'', food:'', spend:'', rating:'' };

function date(value:string){ return new Date(`${value}T12:00:00`); }
function today(){ const n=new Date(); return new Date(n.getFullYear(),n.getMonth(),n.getDate(),12); }
function phase(){ const now=today(), start=date(trip.startDate), end=date(trip.endDate); const active=trip.days.filter(d=>now>=date(d.date)&&(d.end?now<date(d.end):now<=date(d.date))); const current=active.at(-1); const next=trip.days.find(d=>date(d.date)>now); if(now<start)return{kind:'before' as const,count:Math.round((+start-+now)/86400000),current:null,next:trip.days[0]}; if(now>end)return{kind:'after' as const,count:Math.round((+now-+end)/86400000),current:null,next:null}; return{kind:'during' as const,count:Math.round((+now-+start)/86400000)+1,current:current||next||trip.days.at(-1)!,next}; }

export default function AtlasApp(){
  const [view,setView]=useState<View>('today');
  const [state,setState]=useState<SavedState>(initial);
  const [hydrated,setHydrated]=useState(false);
  useEffect(()=>{ try{ const raw=localStorage.getItem(storageKey); if(raw){ const saved=JSON.parse(raw) as Partial<SavedState>; setState({ checks:saved.checks&&typeof saved.checks==='object'?saved.checks:{}, selectedDayId:typeof saved.selectedDayId==='string'?saved.selectedDayId:initial.selectedDayId, journal:saved.journal&&typeof saved.journal==='object'?saved.journal:{} }); } }catch{ localStorage.removeItem(storageKey); }finally{setHydrated(true)} },[]);
  useEffect(()=>{ if(hydrated)localStorage.setItem(storageKey,JSON.stringify(state)); },[state,hydrated]);
  const moment=phase();
  const allChecks=trip.checklists.flatMap(g=>g.items);
  const done=allChecks.filter(i=>state.checks[i.id]).length;
  const score=Math.round(done/Math.max(allChecks.length,1)*100);
  const open=trip.bookings.filter(b=>b.status==='open');
  const selected=trip.days.find(d=>d.id===state.selectedDayId)||trip.days[0];
  const captured=Object.values(state.journal).filter(e=>Object.values(e).some(Boolean)).length;
  const spend=Object.values(state.journal).reduce((sum,e)=>sum+(Number(e.spend)||0),0);
  const priorities=[...open.map(b=>({title:b.title,note:b.notes})),...allChecks.filter(i=>!state.checks[i.id]).map(i=>({title:i.label,note:i.note}))].slice(0,4);
  const briefing=moment.kind==='before'?`${moment.count} days until departure. Close the remaining booking and transport gaps first.`:moment.kind==='during'?`Trip day ${moment.count}: ${moment.current.title}. ${moment.current.detail}`:'The journey is complete. Your notes and memories remain in Atlas.';

  function chooseDay(day:TripDay){ setState(s=>({...s,selectedDayId:day.id})); }
  function updateJournal(field:keyof JournalEntry,value:string){ setState(s=>({...s,journal:{...s.journal,[selected.id]:{...(s.journal[selected.id]??emptyJournalEntry),[field]:value}}})); }
  const entry=state.journal[selected.id]??emptyJournalEntry;

  return <div className="atlas-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">A</span><div><h1>Atlas</h1><p>{trip.title} · {trip.subtitle}</p></div></div><nav className="tabs">{(['today','trip','map','bookings','readiness','journal'] as View[]).map(v=><button key={v} className={`tab ${view===v?'active':''}`} onClick={()=>setView(v)}>{v==='readiness'?'Mission Control':v[0].toUpperCase()+v.slice(1)}</button>)}</nav></header>
    <main>
      {view==='today'&&<section className="view active page"><div className="hero"><div><span className="eyebrow">Your travel command center</span><h2>{trip.title}</h2><p>{briefing}</p></div><div className="hero-score"><span>{score}%</span><small>ready</small></div></div><div className="metric-grid"><div className="metric"><b>{moment.count}</b><span>{moment.kind==='before'?'days to departure':moment.kind==='during'?'trip day':'days since return'}</span></div><div className="metric"><b>{trip.days.length}</b><span>itinerary stops</span></div><div className="metric"><b>{trip.bookings.length-open.length}</b><span>confirmed bookings</span></div><div className="metric"><b>{captured}</b><span>journal days captured</span></div></div><div className="dashboard-grid"><section className="panel"><span className="eyebrow">Atlas briefing</span><h2>{moment.kind==='before'?'Departure intelligence':moment.kind==='during'?moment.current.title:'Welcome home'}</h2><p>{briefing}</p><button className="primary" onClick={()=>setView(moment.kind==='after'?'journal':moment.kind==='before'?'readiness':'trip')}>{moment.kind==='after'?'Open journal':moment.kind==='before'?'Open Mission Control':'Open today’s plan'}</button></section><section className="panel"><span className="eyebrow">Ranked priority</span><h3>What matters next</h3><div className="stack">{priorities.length?priorities.map((p,i)=><div className="issue" key={p.title}><b>{i+1}. {p.title}</b><div className="muted">{p.note}</div></div>):<div className="win">Atlas found nothing urgent.</div>}</div></section></div></section>}
      {view==='trip'&&<section className="view active page"><div className="page-head"><div><span className="eyebrow">Day by day</span><h2>Full itinerary</h2><p>Typed React components now drive the itinerary.</p></div></div><div className="trip-layout"><div className="timeline">{trip.days.map(day=><button key={day.id} className={`timeline-item ${selected.id===day.id?'active':''}`} onClick={()=>chooseDay(day)}><span className="date">{day.label}</span><span className="dot"/><span className="timeline-card"><b>{day.title}</b><span>{day.place}</span></span></button>)}</div><aside className="panel sticky"><span className="eyebrow">{selected.label}</span><h2>{selected.title}</h2><p className="muted">{selected.place}</p><span className={`status-pill ${selected.status==='booked'?'good':'warn'}`}>{selected.status}</span><div className="detail-list"><div className="detail-row"><small>Plan</small>{selected.detail}</div>{selected.confirmation&&<div className="detail-row"><small>Confirmation</small><b>{selected.confirmation}</b></div>}<div className="detail-row"><small>Journal</small>{entry.notes||entry.moment||'No memory recorded yet.'}</div></div><button onClick={()=>setView('journal')}>Write journal</button></aside></div></section>}
      {view==='map'&&<section className="view active route-grid"><aside className="map-rail panel"><span className="eyebrow">Route</span><h2>15-day journey</h2><div className="stack">{trip.days.map((d,i)=><div className="stop-card" key={d.id}><span className="stop-num">{i+1}</span><div><b>{d.title}</b><span>{d.label} · {d.place}</span></div></div>)}</div></aside><TripMap days={trip.days}/></section>}
      {view==='bookings'&&<section className="view active page"><div className="page-head"><div><span className="eyebrow">Vault</span><h2>Bookings & documents</h2></div></div><div className="booking-grid">{trip.bookings.map(b=><article className="booking-card" key={b.title}><span className="eyebrow">{b.category}</span><h3>{b.title}</h3><p>{b.date}</p><span className={`status-pill ${b.status==='booked'?'good':'warn'}`}>{b.status}</span>{b.confirmation&&<span className="status-pill"># {b.confirmation}</span>}<p>{b.notes}</p></article>)}</div></section>}
      {view==='readiness'&&<section className="view active page"><div className="page-head"><div><span className="eyebrow">Mission Control</span><h2>Trip readiness</h2></div></div><div className="readiness-hero panel"><div><span className="eyebrow">Readiness score</span><div className="score">{score}%</div></div><div className="progress-wrap"><div className="progress"><span style={{width:`${score}%`}}/></div><small>{done} of {allChecks.length} complete</small></div></div><div className="check-grid">{trip.checklists.map(g=><section className="panel check-group" key={g.group}><h3>{g.group}</h3>{g.items.map(i=><div className="check-row" key={i.id}><input type="checkbox" checked={!!state.checks[i.id]} onChange={e=>setState(s=>({...s,checks:{...s.checks,[i.id]:e.target.checked}}))}/><label>{i.label}<small>{i.note}</small></label></div>)}</section>)}</div></section>}
      {view==='journal'&&<section className="view active page"><div className="page-head"><div><span className="eyebrow">Memory layer</span><h2>Trip journal</h2><p>Stored privately in this browser.</p></div></div><div className="metric-grid"><div className="metric"><b>{captured}</b><span>days captured</span></div><div className="metric"><b>${spend.toFixed(0)}</b><span>recorded spend</span></div><div className="metric"><b>{trip.days.length-captured}</b><span>days unwritten</span></div><div className="metric"><b>{trip.days.length}</b><span>journey stops</span></div></div><div className="trip-layout"><div className="timeline">{trip.days.map(d=><button key={d.id} className={`timeline-item ${selected.id===d.id?'active':''}`} onClick={()=>chooseDay(d)}><span className="date">{d.label}</span><span className="dot"/><span className="timeline-card"><b>{d.title}</b><span>{state.journal[d.id]?.moment||'Write this day'}</span></span></button>)}</div><aside className="panel sticky journal-form"><span className="eyebrow">{selected.label}</span><h2>{selected.title}</h2><label>Notes<textarea className="field" value={entry.notes} onChange={e=>updateJournal('notes',e.target.value)}/></label><label>Favorite moment<input className="field" value={entry.moment} onChange={e=>updateJournal('moment',e.target.value)}/></label><div className="form-grid"><label>Food or drink<input className="field" value={entry.food} onChange={e=>updateJournal('food',e.target.value)}/></label><label>Spend<input className="field" type="number" value={entry.spend} onChange={e=>updateJournal('spend',e.target.value)}/></label></div><label>Rating<select className="field" value={entry.rating} onChange={e=>updateJournal('rating',e.target.value)}><option value="">Choose</option>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><small className="muted">Saved automatically.</small></aside></div></section>}
    </main>
  </div>;
}
