'use client';

import dynamic from 'next/dynamic';
import { useEffect, useMemo, useState } from 'react';
import { trip, type Booking, type TripDay } from '@/lib/trip';

const TripMap = dynamic(() => import('./TripMap'), { ssr:false, loading:() => <div className="empty-state">Loading route map…</div> });
type View = 'today'|'trip'|'map'|'bookings'|'readiness'|'agent'|'journal';
type JournalEntry = { notes:string; moment:string; food:string; spend:string; rating:string };
type EditableBooking = Booking & { id:string; dayId?:string };
type SavedState = { checks:Record<string,boolean>; selectedDayId:string; journal:Record<string,JournalEntry>; days:TripDay[]; bookings:EditableBooking[] };
type DraftStop = { title:string; place:string; date:string; end:string; lat:string; lng:string; type:string };
type Proposal = { message:string; action?:'remove'|'add'; target?:string; stop?:TripDay };

const seededBookings:EditableBooking[] = trip.bookings.map((booking,index)=>({ ...booking,id:`seed-${index}` }));
const initial:SavedState = { checks:{}, selectedDayId:trip.days[0].id, journal:{}, days:trip.days, bookings:seededBookings };
const emptyJournalEntry:JournalEntry = { notes:'',moment:'',food:'',spend:'',rating:'' };
const emptyDraft:DraftStop = { title:'',place:'',date:'',end:'',lat:'',lng:'',type:'hotel' };
const storageKey = `atlas:${trip.id}:planner-v1`;

function asDate(value:string){ return new Date(`${value}T12:00:00`); }
function nowDate(){ const n=new Date(); return new Date(n.getFullYear(),n.getMonth(),n.getDate(),12); }
function makeId(prefix:string){ return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`; }

export default function AtlasApp(){
  const [view,setView]=useState<View>('today');
  const [state,setState]=useState<SavedState>(initial);
  const [hydrated,setHydrated]=useState(false);
  const [showEditor,setShowEditor]=useState(false);
  const [editingId,setEditingId]=useState<string|null>(null);
  const [draft,setDraft]=useState<DraftStop>(emptyDraft);
  const [agentPrompt,setAgentPrompt]=useState('');
  const [proposal,setProposal]=useState<Proposal>({message:'Tell me what you want to change. I can add or remove destinations, find booking gaps, or make the trip less rushed.'});
  const [agentBusy,setAgentBusy]=useState(false);

  useEffect(()=>{ try{ const raw=localStorage.getItem(storageKey); if(raw){ const saved=JSON.parse(raw) as Partial<SavedState>; setState({ checks:saved.checks??{}, selectedDayId:saved.selectedDayId??initial.selectedDayId, journal:saved.journal??{}, days:Array.isArray(saved.days)?saved.days:initial.days, bookings:Array.isArray(saved.bookings)?saved.bookings:initial.bookings }); } }catch{ localStorage.removeItem(storageKey); }finally{setHydrated(true)} },[]);
  useEffect(()=>{ if(hydrated)localStorage.setItem(storageKey,JSON.stringify(state)); },[state,hydrated]);

  const allChecks=trip.checklists.flatMap(group=>group.items);
  const done=allChecks.filter(item=>state.checks[item.id]).length;
  const score=Math.round(done/Math.max(allChecks.length,1)*100);
  const open=state.bookings.filter(booking=>booking.status==='open');
  const selected=state.days.find(day=>day.id===state.selectedDayId)??state.days[0];
  const captured=Object.values(state.journal).filter(entry=>Object.values(entry).some(Boolean)).length;
  const spend=Object.values(state.journal).reduce((sum,entry)=>sum+(Number(entry.spend)||0),0);
  const entry=state.journal[selected?.id]??emptyJournalEntry;
  const moment=useMemo(()=>{ const now=nowDate(), start=asDate(trip.startDate), end=asDate(trip.endDate); const active=state.days.filter(day=>now>=asDate(day.date)&&(day.end?now<asDate(day.end):now<=asDate(day.date))).at(-1); const next=state.days.find(day=>asDate(day.date)>now); if(now<start)return{kind:'before' as const,count:Math.round((+start-+now)/86400000),current:state.days[0]}; if(now>end)return{kind:'after' as const,count:Math.round((+now-+end)/86400000),current:state.days.at(-1)}; return{kind:'during' as const,count:Math.round((+now-+start)/86400000)+1,current:active??next??state.days.at(-1)}; },[state.days]);
  const briefing=moment.kind==='before'?`${moment.count} days until departure. ${open.length?`${open.length} booking decisions remain.`:'Your core bookings are covered.'}`:moment.kind==='during'?`Trip day ${moment.count}: ${moment.current?.title}. ${moment.current?.detail}`:'The journey is complete. Your notes remain in Atlas.';
  const priorities=[...open.map(b=>({title:b.title,note:b.notes})),...allChecks.filter(i=>!state.checks[i.id]).map(i=>({title:i.label,note:i.note}))].slice(0,4);

  function chooseDay(day:TripDay){ setState(current=>({...current,selectedDayId:day.id})); }
  function updateJournal(field:keyof JournalEntry,value:string){ if(!selected)return; setState(current=>({...current,journal:{...current.journal,[selected.id]:{...(current.journal[selected.id]??emptyJournalEntry),[field]:value}}})); }
  function openNewStop(){ setEditingId(null); setDraft(emptyDraft); setShowEditor(true); }
  function openEditStop(day:TripDay){ setEditingId(day.id); setDraft({title:day.title,place:day.place,date:day.date,end:day.end??'',lat:String(day.lat),lng:String(day.lng),type:day.type}); setShowEditor(true); }
  async function locate(place:string){ const response=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${encodeURIComponent(place)}`); const result=await response.json() as Array<{lat:string;lon:string}>; if(!result[0])throw new Error('Location not found'); return{lat:Number(result[0].lat),lng:Number(result[0].lon)}; }
  async function saveStop(){
    if(!draft.title||!draft.place||!draft.date)return;
    let lat=Number(draft.lat),lng=Number(draft.lng);
    if(!Number.isFinite(lat)||!Number.isFinite(lng)||(!lat&&!lng)){ try{({lat,lng}=await locate(draft.place));}catch{return;} }
    const day:TripDay={id:editingId??makeId('stop'),title:draft.title,place:draft.place,date:draft.date,end:draft.end||undefined,label:draft.end?`${draft.date} – ${draft.end}`:draft.date,lat,lng,type:draft.type,detail:`Plan your time in ${draft.place}.`,status:'open'};
    setState(current=>{
      const days=(editingId?current.days.map(item=>item.id===editingId?day:item):[...current.days,day]).sort((a,b)=>a.date.localeCompare(b.date));
      const newBooking:EditableBooking={id:makeId('booking'),dayId:day.id,title:`${day.title} lodging`,category:'Lodging',status:'open',date:day.label,notes:`Choose and confirm a stay in ${day.place}.`};
      const bookings=draft.type==='hotel'&&!current.bookings.some(item=>item.dayId===day.id)?[...current.bookings,newBooking]:current.bookings.map(item=>item.dayId===day.id?{...item,title:`${day.title} lodging`,date:day.label}:item);
      return{...current,days,bookings,selectedDayId:day.id};
    });
    setShowEditor(false); setView('trip');
  }
  function removeStop(id:string){ setState(current=>{ const days=current.days.filter(day=>day.id!==id); return{...current,days,bookings:current.bookings.filter(booking=>booking.dayId!==id),selectedDayId:days[0]?.id??''}; }); }
  function updateBooking(id:string,patch:Partial<EditableBooking>){ setState(current=>({...current,bookings:current.bookings.map(booking=>booking.id===id?{...booking,...patch}:booking)})); }

  async function askAgent(prompt=agentPrompt){
    const text=prompt.trim(); if(!text)return; setAgentBusy(true); const lower=text.toLowerCase();
    const removeMatch=lower.match(/(?:remove|skip|delete)\s+(.+)/i);
    const addMatch=text.match(/(?:add|visit|include)\s+(.+)/i);
    if(removeMatch){ const target=state.days.find(day=>day.title.toLowerCase().includes(removeMatch[1].trim())||day.place.toLowerCase().includes(removeMatch[1].trim())); setProposal(target?{message:`I found ${target.title}. Removing it will also remove any lodging card linked to that stop.`,action:'remove',target:target.id}:{message:`I couldn't match “${removeMatch[1].trim()}” to a current destination.`}); }
    else if(addMatch){ const place=addMatch[1].replace(/[?.!]/g,'').trim(); try{ const coords=await locate(place); const last=state.days.at(-1); const date=last?.date??trip.startDate; setProposal({message:`I found ${place}. I can add it to the route as an unbooked destination; you can fine-tune its date afterward.`,action:'add',stop:{id:makeId('agent-stop'),title:place,place,date,label:date,lat:coords.lat,lng:coords.lng,type:'hotel',detail:`New destination suggested by Atlas Agent.`,status:'open'}}); }catch{setProposal({message:`I couldn't locate ${place}. Try a city plus country, such as “add Oban, Scotland.”`});} }
    else if(lower.includes('rushed')||lower.includes('slow')){ const quick=state.days.filter(day=>day.end&&Math.round((+asDate(day.end)-+asDate(day.date))/86400000)<=1); setProposal({message:quick.length?`The tightest stays are ${quick.map(day=>day.title).join(', ')}. I’d protect Dingle and Edinburgh first, then consider removing a one-night transfer stop.`:'Your overnight pacing looks reasonable. The longest pressure point is likely travel time rather than hotel changes.'}); }
    else if(lower.includes('booking')||lower.includes('book'))setProposal({message:open.length?`You have ${open.length} open items: ${open.map(item=>item.title).join(', ')}. Open Bookings to confirm or remove them.`:'All tracked bookings are marked confirmed.'});
    else setProposal({message:`I can act on requests like “add Oban, Scotland,” “remove Glasgow,” “find booking gaps,” or “make the trip less rushed.” I’ll always show the change before applying it.`});
    setAgentBusy(false); setAgentPrompt('');
  }
  function applyProposal(){ if(proposal.action==='remove'&&proposal.target)removeStop(proposal.target); if(proposal.action==='add'&&proposal.stop){ const stop=proposal.stop; const booking:EditableBooking={id:makeId('booking'),dayId:stop.id,title:`${stop.title} lodging`,category:'Lodging',status:'open',date:stop.label,notes:`Choose and confirm a stay in ${stop.place}.`}; setState(current=>({...current,days:[...current.days,stop].sort((a,b)=>a.date.localeCompare(b.date)),bookings:[...current.bookings,booking],selectedDayId:stop.id})); } setProposal({message:'Done. The itinerary, map, and booking coverage have been updated.'}); }

  return <div className="atlas-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">A</span><div><h1>Atlas</h1><p>{trip.title} · {trip.subtitle}</p></div></div><nav className="tabs">{(['today','trip','map','bookings','readiness','agent','journal'] as View[]).map(item=><button key={item} className={`tab ${view===item?'active':''}`} onClick={()=>setView(item)}>{item==='readiness'?'Ready':item[0].toUpperCase()+item.slice(1)}</button>)}</nav></header>
    <main>
      {view==='today'&&<section className="view active page"><div className="hero"><div><span className="eyebrow">Your journey, live</span><h2>{trip.title}</h2><p>{briefing}</p></div><div className="hero-score"><span>{score}%</span><small>ready</small></div></div><div className="metric-grid"><div className="metric"><b>{moment.count}</b><span>{moment.kind==='before'?'days to departure':moment.kind==='during'?'trip day':'days since return'}</span></div><div className="metric"><b>{state.days.length}</b><span>route moments</span></div><div className="metric"><b>{state.bookings.length-open.length}</b><span>confirmed bookings</span></div><div className="metric"><b>{captured}</b><span>journal days</span></div></div><div className="dashboard-grid"><section className="panel"><span className="eyebrow">Next move</span><h2>{moment.current?.title??'Plan the journey'}</h2><p>{briefing}</p><div className="action-row"><button className="primary" onClick={()=>setView('trip')}>Open itinerary</button><button onClick={()=>setView('agent')}>Ask Atlas Agent</button></div></section><section className="panel"><span className="eyebrow">Priority</span><h3>What needs attention</h3><div className="stack">{priorities.length?priorities.map((item,index)=><div className="issue" key={`${item.title}-${index}`}><b>{item.title}</b><div className="muted">{item.note}</div></div>):<div className="win">Nothing urgent.</div>}</div></section></div></section>}
      {view==='trip'&&<section className="view active page"><div className="page-head"><div><span className="eyebrow">Editable itinerary</span><h2>Build your route.</h2><p>Add, edit, or remove destinations. Atlas keeps the map and lodging coverage in sync.</p></div><button className="primary" onClick={openNewStop}>Add destination</button></div><div className="trip-layout"><div className="timeline">{state.days.map(day=><button key={day.id} className={`timeline-item ${selected?.id===day.id?'active':''}`} onClick={()=>chooseDay(day)}><span className="date">{day.label}</span><span className="dot"/><span className="timeline-card"><b>{day.title}</b><span>{day.place}</span></span></button>)}</div>{selected&&<aside className="panel sticky"><span className="eyebrow">{selected.label}</span><h2>{selected.title}</h2><p className="muted">{selected.place}</p><span className={`status-pill ${selected.status==='booked'?'good':'warn'}`}>{selected.status}</span><div className="detail-list"><div className="detail-row"><small>Plan</small>{selected.detail}</div><div className="detail-row"><small>Journal</small>{entry.notes||entry.moment||'No memory recorded yet.'}</div></div><div className="action-row"><button className="primary" onClick={()=>openEditStop(selected)}>Edit</button><button className="danger" onClick={()=>removeStop(selected.id)}>Remove</button></div></aside>}</div></section>}
      {view==='map'&&<section className="view active route-grid"><aside className="map-rail panel"><span className="eyebrow">Live route</span><h2>{state.days.length} moments</h2><button className="primary wide" onClick={openNewStop}>Add destination</button><div className="stack map-stops">{state.days.map((day,index)=><button className="stop-card" key={day.id} onClick={()=>{chooseDay(day);setView('trip')}}><span className="stop-num">{index+1}</span><div><b>{day.title}</b><span>{day.label} · {day.place}</span></div></button>)}</div></aside><TripMap days={state.days}/></section>}
      {view==='bookings'&&<section className="view active page"><div className="page-head"><div><span className="eyebrow">Reactive coverage</span><h2>Bookings.</h2><p>New overnight destinations automatically create an open lodging item.</p></div></div><div className="booking-grid">{state.bookings.map(booking=><article className="booking-card" key={booking.id}><span className="eyebrow">{booking.category}</span><h3>{booking.title}</h3><p>{booking.date}</p><span className={`status-pill ${booking.status==='booked'?'good':'warn'}`}>{booking.status}</span>{booking.confirmation&&<span className="status-pill"># {booking.confirmation}</span>}<p>{booking.notes}</p><div className="action-row"><button onClick={()=>updateBooking(booking.id,{status:booking.status==='booked'?'open':'booked'})}>{booking.status==='booked'?'Mark open':'Mark confirmed'}</button><button className="danger" onClick={()=>setState(current=>({...current,bookings:current.bookings.filter(item=>item.id!==booking.id)}))}>Remove</button></div></article>)}</div></section>}
      {view==='readiness'&&<section className="view active page"><div className="page-head"><div><span className="eyebrow">Mission control</span><h2>Ready to go.</h2></div></div><div className="readiness-hero panel"><div><span className="eyebrow">Readiness</span><div className="score">{score}%</div></div><div className="progress-wrap"><div className="progress"><span style={{width:`${score}%`}}/></div><small>{done} of {allChecks.length} complete</small></div></div><div className="check-grid">{trip.checklists.map(group=><section className="panel check-group" key={group.group}><h3>{group.group}</h3>{group.items.map(item=><div className="check-row" key={item.id}><input id={item.id} type="checkbox" checked={!!state.checks[item.id]} onChange={event=>setState(current=>({...current,checks:{...current.checks,[item.id]:event.target.checked}}))}/><label htmlFor={item.id}>{item.label}<small>{item.note}</small></label></div>)}</section>)}</div></section>}
      {view==='agent'&&<section className="view active page agent-page"><div className="agent-intro"><span className="agent-orb">A</span><span className="eyebrow">Atlas Agent</span><h2>Your travel planner,<br/>inside the trip.</h2><p>Ask for route changes, pacing advice, or booking coverage. Atlas proposes edits first—you decide what gets applied.</p></div><section className="agent-console panel"><div className="agent-message">{proposal.message}</div>{proposal.action&&<div className="proposal-card"><span className="status-pill warn">Proposed change</span><b>{proposal.action==='remove'?'Remove destination':'Add destination'}</b><button className="primary" onClick={applyProposal}>Apply change</button></div>}<div className="quick-prompts">{['Find booking gaps','Make the trip less rushed','Add Oban, Scotland','Remove Glasgow'].map(prompt=><button key={prompt} onClick={()=>askAgent(prompt)}>{prompt}</button>)}</div><div className="agent-input"><textarea value={agentPrompt} onChange={event=>setAgentPrompt(event.target.value)} placeholder="Try: Add Inverness, Scotland"/><button className="primary" disabled={agentBusy} onClick={()=>askAgent()}>{agentBusy?'Thinking…':'Ask Atlas'}</button></div></section></section>}
      {view==='journal'&&<section className="view active page"><div className="page-head"><div><span className="eyebrow">Memory layer</span><h2>Trip journal.</h2><p>Saved privately in this browser.</p></div></div><div className="metric-grid"><div className="metric"><b>{captured}</b><span>days captured</span></div><div className="metric"><b>${spend.toFixed(0)}</b><span>recorded spend</span></div><div className="metric"><b>{Math.max(state.days.length-captured,0)}</b><span>days unwritten</span></div><div className="metric"><b>{state.days.length}</b><span>journey moments</span></div></div><div className="trip-layout"><div className="timeline">{state.days.map(day=><button key={day.id} className={`timeline-item ${selected?.id===day.id?'active':''}`} onClick={()=>chooseDay(day)}><span className="date">{day.label}</span><span className="dot"/><span className="timeline-card"><b>{day.title}</b><span>{state.journal[day.id]?.moment||'Write this day'}</span></span></button>)}</div>{selected&&<aside className="panel sticky journal-form"><span className="eyebrow">{selected.label}</span><h2>{selected.title}</h2><label>Notes<textarea className="field" value={entry.notes} onChange={event=>updateJournal('notes',event.target.value)}/></label><label>Favorite moment<input className="field" value={entry.moment} onChange={event=>updateJournal('moment',event.target.value)}/></label><div className="form-grid"><label>Food or drink<input className="field" value={entry.food} onChange={event=>updateJournal('food',event.target.value)}/></label><label>Spend<input className="field" type="number" value={entry.spend} onChange={event=>updateJournal('spend',event.target.value)}/></label></div><label>Rating<select className="field" value={entry.rating} onChange={event=>updateJournal('rating',event.target.value)}><option value="">Choose</option>{[1,2,3,4,5].map(value=><option key={value}>{value}</option>)}</select></label><small className="muted">Saved automatically.</small></aside>}</div></section>}
    </main>
    {showEditor&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setShowEditor(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="stop-title" onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">Route editor</span><h2 id="stop-title">{editingId?'Edit destination':'Add destination'}</h2></div><button aria-label="Close" onClick={()=>setShowEditor(false)}>Close</button></div><div className="editor-grid"><label>Name<input value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})} placeholder="Oban"/></label><label>Location<input value={draft.place} onChange={event=>setDraft({...draft,place:event.target.value})} placeholder="Oban, Scotland"/></label><label>Start date<input type="date" value={draft.date} onChange={event=>setDraft({...draft,date:event.target.value})}/></label><label>End / checkout<input type="date" value={draft.end} onChange={event=>setDraft({...draft,end:event.target.value})}/></label><label>Type<select value={draft.type} onChange={event=>setDraft({...draft,type:event.target.value})}><option value="hotel">Overnight destination</option><option value="activity">Activity / day trip</option><option value="train">Train</option><option value="ferry">Ferry</option><option value="car">Car / transfer</option></select></label><div className="coordinate-note">Atlas will locate the destination automatically. Coordinates are optional.</div><label>Latitude (optional)<input value={draft.lat} onChange={event=>setDraft({...draft,lat:event.target.value})}/></label><label>Longitude (optional)<input value={draft.lng} onChange={event=>setDraft({...draft,lng:event.target.value})}/></label></div><button className="primary wide" onClick={saveStop}>{editingId?'Save changes':'Add to trip'}</button></section></div>}
  </div>;
}
